/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_electron_Injector */

#ifndef _Included_com_electron_Injector
#define _Included_com_electron_Injector
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_electron_Injector
	 * Method:    inject
	 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_electron_Injector_inject
	(JNIEnv*, jclass, jstring, jstring);

	/*
	 * Class:     com_electron_Injector
	 * Method:    additionalProgram
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_electron_Injector_additionalProgram
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     com_electron_Injector
	 * Method:    executeJavascript
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_com_electron_Injector_executeJavascript
	(JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
