/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_electron_InjectorHook */

#ifndef _Included_com_electron_InjectorHook
#define _Included_com_electron_InjectorHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_electron_InjectorHook
 * Method:    initCompilationHook
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_electron_InjectorHook_initCompilationHook
  (JNIEnv *, jclass, jstring);

/*
* Class:     com_electron_InjectorHook
* Method:    initMessageHook
* Signature: (Ljava/lang/String;)Z
*/
JNIEXPORT jboolean JNICALL Java_com_electron_InjectorHook_initMessageHook(
	JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
